# Generated by Django 5.2 on 2025-05-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="home_gym",
            field=models.CharField(
                default="Powerhouse", max_length=100, verbose_name="Home Gym?"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="record",
            name="active",
            field=models.BooleanField(
                default=False, verbose_name="Is your child currently in gymnastics?"
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="age",
            field=models.PositiveIntegerField(verbose_name="Child's Age"),
        ),
        migrations.AlterField(
            model_name="record",
            name="challenges",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Challenges Faced"
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="competitive",
            field=models.BooleanField(
                default=False, verbose_name="Do they compete in competitions?"
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email Address"),
        ),
        migrations.AlterField(
            model_name="record",
            name="level",
            field=models.CharField(
                blank=True,
                max_length=50,
                verbose_name="Competitive Level (Level/Xcel/IGH)",
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Full Name"),
        ),
        migrations.AlterField(
            model_name="record",
            name="phone",
            field=models.CharField(max_length=20, verbose_name="Phone Number"),
        ),
        migrations.AlterField(
            model_name="record",
            name="recommendations",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Recommendations"
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="resources",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Helpful Resources"
            ),
        ),
    ]
