# Generated by Django 3.0 on 2020-01-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping_Units',
            fields=[
                ('on_hand', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('client', models.CharField(max_length=50)),
                ('sub_client', models.CharField(blank=True, max_length=50, null=True)),
                ('width', models.PositiveIntegerField()),
                ('length', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('gross_weight', models.PositiveIntegerField()),
                ('purpose', models.CharField(max_length=50)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('hawb', models.CharField(blank=True, max_length=50, null=True)),
                ('mawb', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ('release_date',),
            },
        ),
    ]
