# Generated by Django 3.0 on 2020-01-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping_units',
            name='purpose',
            field=models.CharField(choices=[('export', 'Export'), ('domestic', 'Domestic'), ('other', 'Other')], default='other', max_length=10),
        ),
    ]
