# Generated by Django 3.0 on 2020-01-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_auto_20200130_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping_units',
            name='purpose',
            field=models.CharField(choices=[('Export', 'Export'), ('Domestic', 'Domestic'), ('Other', 'Other')], default='other', max_length=10),
        ),
    ]
