# Generated by Django 3.0 on 2020-01-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_auto_20200130_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_count', models.PositiveIntegerField()),
                ('date_received', models.DateField(auto_now_add=True)),
                ('permlink', models.SlugField(max_length=250)),
            ],
            options={
                'ordering': ('date_received',),
            },
        ),
        migrations.AlterField(
            model_name='shipping_units',
            name='purpose',
            field=models.CharField(choices=[('Export', 'Export'), ('Domestic', 'Domestic'), ('Other', 'Other')], default='Other', max_length=10),
        ),
    ]
