# Generated by Django 3.0 on 2020-01-31 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_auto_20200131_1039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inboundunits',
            name='permlink',
        ),
    ]
