# Generated by Django 3.0 on 2020-01-31 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0005_remove_inboundunits_permlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipping_units',
            options={'ordering': ('release_date',), 'permissions': (('can_add_shipment', 'Can add a shipping unit'),)},
        ),
    ]
