# Generated by Django 3.0 on 2020-02-01 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0006_auto_20200131_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inboundunits',
            options={'ordering': ('date_received',), 'permissions': (('can_add_delivery', 'Can add delivery'), ('can_edit_delivery', 'Can edit delivery'))},
        ),
        migrations.AlterModelOptions(
            name='shipping_units',
            options={'ordering': ('release_date',), 'permissions': (('can_add_shipment', 'Can add a shipping unit'), ('can_modify', 'Can modify a shipment'), ('can_release', 'Can release a shipment'), ('can delete', 'Can erase a shipment from existence'))},
        ),
    ]
