# Generated by Django 3.0 on 2020-02-01 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0007_auto_20200131_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipping_units',
            options={'ordering': ('release_date',), 'permissions': (('can_add_shipment', 'Can add a shipping unit'), ('can_modify', 'Can modify a shipment'), ('can_release', 'Can release a shipment'), ('can_delete', 'Can erase a shipment from existence'))},
        ),
    ]
